[package]
name = "myhooking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]


[dependencies]
winapi = {version = "0.3.9",features = [
    "processthreadsapi","memoryapi","errhandlingapi","handleapi",
    "securitybaseapi","sddl","winbase","winnt","ntlsa","synchapi",
    "tlhelp32","winerror","memoryapi","minwinbase",
    "fileapi","ntdef","winuser","minwindef","lsalookup",
    "libloaderapi"
    
]}
ntapi = "0.4.1"
itertools = "0.12.0"
